1. Data : Images 
2. Download images manually the image from google 
3. dowload dataset from kaggle.com 
4. Build a image web crawler 
5. Use python library to scrape the images (using) 

In [1]:
!pip install bing-image-downloader

In [2]:
!mkdir images

A subdirectory or file images already exists.


In [3]:
from bing_image_downloader import downloader
downloader.download("pretty sunflower", limit=30, output_dir='images',adult_filter_off=True)



[!!]Indexing page: 1

[%] Indexed 14 Images on Page 1.


[%] Downloading Image #1 from https://i.pinimg.com/736x/9a/e0/5c/9ae05cd6d5cfc4ea71fa68b00c203750--sun-flowers-pretty-flowers.jpg
[%] File Downloaded !

[%] Downloading Image #2 from https://i.pinimg.com/originals/21/c8/e2/21c8e2c6a8ccbdd74c5cf5ffd1b388c6.jpg
[%] File Downloaded !

[%] Downloading Image #3 from https://i.pinimg.com/736x/77/3f/e6/773fe6cd3196fa5240ccad71389f60d3.jpg
[%] File Downloaded !

[%] Downloading Image #4 from https://i.pinimg.com/736x/b6/56/0a/b6560ad58b4e7e418a3dcc03c1ea5db7.jpg
[%] File Downloaded !

[%] Downloading Image #5 from https://i.pinimg.com/originals/04/24/3f/04243f00fb840dbb79f197339ea31830.jpg
[%] File Downloaded !

[%] Downloading Image #6 from http://bestanimations.com/Nature/Flora/beautiful-flower-animated-gif5.gif
[%] File Downloaded !

[%] Downloading Image #7 from https://www.bing.com/th/id/OGC.e05f040180d53eea684e8bd417ae1906?pid=1.7&amp;rurl=http%3a%2f%2fbestanimations.com%2fNature

In [4]:
downloader.download("rugby ball leather", limit=30, output_dir='images',adult_filter_off=True)



[!!]Indexing page: 1

[%] Indexed 12 Images on Page 1.


[%] Downloading Image #1 from https://cdn.notonthehighstreet.com/system/product_images/images/000/393/351/original_CF016852.jpg
[%] File Downloaded !

[%] Downloading Image #2 from https://c1.staticflickr.com/3/2319/5810298255_1e031e64e5_b.jpg
[%] File Downloaded !

[%] Downloading Image #3 from https://media.gq-magazine.co.uk/photos/5d1397242881cc0ab70a8266/16:9/w_1920,c_limit/Rugby-ball-HP-GQ-01Oct15_b.jpg
[%] File Downloaded !

[%] Downloading Image #4 from https://images.antiquesatlas.com/dealer-stock-images/puckeringsantiques/Antique_Novelty_Travel_Inkwell_as584a1568z-3.jpg
[%] File Downloaded !

[%] Downloading Image #5 from http://cdn.shopify.com/s/files/1/0020/1025/1324/products/32p_black_1024x.png?v=1534865418
[%] File Downloaded !

[%] Downloading Image #6 from http://www.john-woodbridge.com/1009-tm_large_default/1930s-football.jpg
[%] File Downloaded !

[%] Downloading Image #7 from http://www.upfrontcricket.com/medi

In [5]:
downloader.download("ice cream cone", limit=30, output_dir='images',adult_filter_off=True)



[!!]Indexing page: 1

[%] Indexed 13 Images on Page 1.


[%] Downloading Image #1 from https://cdn001.cakecentral.com/gallery/2017/07/900_melting-ice-cream-cone-997041mFIfl.jpg
[%] File Downloaded !

[%] Downloading Image #2 from https://www.intimateweddings.com/wp-content/uploads/2011/04/french-fry-cones.jpg
[%] File Downloaded !

[%] Downloading Image #3 from https://superradnow.files.wordpress.com/2012/01/2437209248_b85e658e0c.jpg
[%] File Downloaded !

[%] Downloading Image #4 from https://splashysplash.com/wp-content/uploads/2012/04/gucci-mane-ice-cream-cone-piece-white-diamonds-jewelry-brick-squad-camer-chain.jpeg
[%] File Downloaded !

[%] Downloading Image #5 from http://1.bp.blogspot.com/-FEj_EwKmwsA/UJvWqUqr4FI/AAAAAAAACuw/6lNSLL85pws/s400/popsicle+stick+tree.jpg
[%] File Downloaded !

[%] Downloading Image #6 from https://i.pinimg.com/736x/9a/00/4a/9a004afa9e1ae3371210ce07b4aaaf58--soft-serve-fake-food.jpg
[%] File Downloaded !

[%] Downloading Image #7 from http://bestani

In [6]:
!pip install ipython-autotime
%load_ext autotime

time: 0 ns (started: 2021-02-09 14:14:14 +05:30)


In [7]:
import os
import matplotlib.pyplot as plt
import numpy as np
from skimage.io import imread
from skimage.transform import resize

target = []
images = []
flat_data = []

DATADIR = 'C:\\Users\Hp\images'
CATEGORIES = ['pretty sunflower', 'rugby ball leather', 'ice cream cone']

for category in CATEGORIES:
    class_num = CATEGORIES.index(category)  # label encoding the values
    path = os.path.join(DATADIR, category)  #Create path to use all the images
    for img in os.listdir(path):
        img_array = imread(os.path.join(path,img))
#         print(img_array)              -- give 2D array
#         print(img_array.shape)        --give size



#         plt.imshow(img_array)          -- show image
#         break                          -- used to shoe only 1 image
        img_resized = resize(img_array,(150,150,3))      # resizing it   #Normalizes the value from o to 1
        flat_data.append(img_resized.flatten())          # faltten it
        images.append(img_resized)                       # appending same to our images
        target.append(class_num)                         # append same to our output array
        
flat_data = np.array(flat_data)                  # if some images left unchange then  we will change it here
target = np.array(target)                        
images = np.array(images)

time: 1min 55s (started: 2021-02-09 14:14:35 +05:30)


In [8]:
flat_data        # bunch of array
flat_data[0] 

array([0.96679739, 0.97464052, 0.96862745, ..., 0.1903268 , 0.19424837,
       0.20993464])

time: 15 ms (started: 2021-02-09 14:16:49 +05:30)


In [9]:
len(flat_data)             # total we have 90 values

135

time: 0 ns (started: 2021-02-09 14:16:50 +05:30)


In [10]:
len(flat_data[0])

67500

time: 0 ns (started: 2021-02-09 14:16:50 +05:30)


In [11]:
target             # we will get 0 - 30times , 1 - 30times, 2 - 30times.

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2])

time: 0 ns (started: 2021-02-09 14:16:52 +05:30)


In [12]:
 np.unique(target,return_counts = True)

(array([0, 1, 2]), array([37, 53, 45], dtype=int64))

time: 0 ns (started: 2021-02-09 14:16:55 +05:30)


In [13]:
unique, count =  np.unique(target,return_counts = True)   
plt.bar(CATEGORIES,count)                                      # plotting bar graph with name vs count

<BarContainer object of 3 artists>

time: 359 ms (started: 2021-02-09 14:16:56 +05:30)


In [14]:
# using sklearn train test split

from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(flat_data,target,test_size=0.3,random_state=109)

time: 1.73 s (started: 2021-02-09 14:17:05 +05:30)


In [15]:
from sklearn.model_selection import GridSearchCV
from sklearn import svm
param_grid = [
                {'C':[1,10,100,1000],'kernel':['linear']},
                {'C':[1,10,100,1000],'gamma':[0.001,0.0001],'kernel':['rbf']}
]

svc = svm.SVC(probability=True)
clf = GridSearchCV(svc,param_grid)
clf.fit(x_train,y_train)

GridSearchCV(estimator=SVC(probability=True),
             param_grid=[{'C': [1, 10, 100, 1000], 'kernel': ['linear']},
                         {'C': [1, 10, 100, 1000], 'gamma': [0.001, 0.0001],
                          'kernel': ['rbf']}])

time: 6min 9s (started: 2021-02-09 14:17:12 +05:30)


In [16]:
y_pred = clf.predict(x_test)
y_pred

array([1, 0, 1, 2, 1, 1, 0, 0, 1, 1, 2, 1, 2, 2, 2, 0, 1, 1, 1, 1, 1, 2,
       1, 1, 2, 1, 0, 2, 1, 0, 1, 1, 2, 1, 2, 2, 2, 1, 1, 2, 0])

time: 531 ms (started: 2021-02-09 14:23:28 +05:30)


In [17]:
y_test

array([1, 0, 2, 2, 1, 0, 0, 0, 1, 1, 2, 2, 2, 1, 1, 0, 2, 1, 1, 1, 1, 1,
       1, 1, 2, 0, 0, 2, 2, 0, 2, 1, 2, 1, 2, 2, 2, 0, 1, 2, 2])

time: 0 ns (started: 2021-02-09 14:23:29 +05:30)


In [18]:
from sklearn.metrics import accuracy_score,confusion_matrix

time: 0 ns (started: 2021-02-09 14:23:31 +05:30)


In [19]:
accuracy_score(y_pred,y_test)                      #goes 70% beacuse data is not refined

0.7073170731707317

time: 0 ns (started: 2021-02-09 14:23:34 +05:30)


In [20]:
confusion_matrix(y_pred,y_test)       #One of the evaulation , which check wheather we get correct output or not

array([[ 6,  0,  1],
       [ 3, 13,  5],
       [ 0,  3, 10]], dtype=int64)

time: 94 ms (started: 2021-02-09 14:23:36 +05:30)


In [21]:
import pickle
pickle.dump(clf,open('image_model.p', 'wb'))

time: 78 ms (started: 2021-02-09 14:23:37 +05:30)


In [22]:
model = pickle.load(open('image_model.p','rb'))     #reading byte

time: 31 ms (started: 2021-02-09 14:23:42 +05:30)


In [23]:
flat_data = []
url = input('Enter you url')
img = imread(url)
img_resized = resize(img,(150,150,3))
flat_data.append(img_resized.flatten())
flat_data = np.array(flat_data)
print(img.shape)
plt.imshow(img_resized)
y_out = model.predict(flat_data)
y_out = CATEGORIES[y_out[0]]
print(f'PREDICTED OUTPUT: {y_out}')

Enter you urlhttps://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ_kXjKZgQnUIBlIVYyXWHpLGCehmHywnzp5g&usqp=CAU
(284, 178, 3)
PREDICTED OUTPUT: ice cream cone


time: 23 s (started: 2021-02-09 14:23:44 +05:30)


Now here we just haveto deployed our code
We can use many different ways to deploy 

    #1 WebApp
    #2 WebPage
    #3 Mobile App